In [46]:
pip install opencv-contrib-python --upgrade  

Requirement already up-to-date: opencv-contrib-python in h:\users\ian\anaconda3\lib\site-packages (4.5.1.48)
Note: you may need to restart the kernel to use updated packages.


In [47]:
import re #for regular expressions to allow sorting the frames

def numberRegex(e):
  #Finding all digits in the filename
  x = re.findall("(\d)", e)

  #if there are two digits in filename
  if(len(x)==2):
      return int(x[0]+""+x[1])
  #if there is one digit in the filename
  else:
      return int(x[0])


In [53]:
import os #Allows reading in file names from local machine
import cv2 as cv #image processing package
import numpy as np

#Directory containing the bmode scans
imageFolder = 'H:/Documents/Github repositories/SE4450-project-code/Preprocessing/P39-W2-S4_Bmode'
vecImageNames = os.listdir(os.path.join(imageFolder)) #vector with the names of the images in the above folder
vecImageNames.sort(key=numberRegex) #Sorts the images by frame number

#Vector containing the path to each image to be processed
vecImagePaths = []
for filename in vecImageNames:
    vecImagePaths.append(imageFolder+"/"+filename)

vecRawImageData = [] #Vector containing the raw data for each image (including scales and title)

for filepath in vecImagePaths: #Reading image data into vector
    vecRawImageData.append(cv.imread(filepath,0))

vecCroppedImageData = [] #Vector containing the images cropped without scales and title
start_row,start_col=int(54),int(95) #Coords for cropping
end_row,end_col=int(670),int(670)

for image in vecRawImageData: #cropping images
    cropped=image[start_row:end_row,start_col:end_col]
    vecCroppedImageData.append(cropped)

M = 8 #number of translations <- LUCAS INPUT HERE
N = len(vecCroppedImageData) #Number of images to translate

#Matrix containing the base center cropped image and each desired translation
matrixTranslatedImages = [ [0 for i in range(M)]] * N 
start_row,start_col=int(10),int(10) #Coordinates for the center crop
end_row,end_col=int(606),int(565)

for i in range(len(vecCroppedImageData)): #'translating' images
    tempImage = vecCroppedImageData[i]
    matrixTranslatedImages[i][0] = tempImage[start_row:end_row,start_col:end_col] 

# cv.imshow('image',matrixTranslatedImages[i][0])  
# cv.waitKey(0) # Waits till keypress  
# cv.destroyAllWindows()


[[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]]
[[255 255 255 ... 228 255 244]
 [255  38  38 ...  41 239 249]
 [255  30  40 ...  39  84 254]
 ...
 [255  35  39 ...  68  56 231]
 [255  44  41 ...  25 231 255]
 [255 255 254 ... 246 255 247]]
[[255 255 255 ... 228 255 244]
 [255  38  38 ...  41 239 249]
 [255  32  39 ...  37  91 250]
 ...
 [255  30  31 ...  69  53 226]
 [255  37  37 ...  22 227 255]
 [255 255 255 ... 246 255 255]]
[[255 255 255 ...

In [49]:
#Choose number of steps to move to generate more data
images = []
steps = 1
#set steps to be maximize size given number of steps
step_size = 10/steps
#move crop around base image to generate more possible correct pairs
for x in range(-steps,steps+1):
    for y in range(-steps,steps+1):
        images.append(cropped[(start_row+y):(end_row+x),(start_col+y):(end_col+x)])